project:
  type: website
  output-dir: docs

website:
  navbar:
    title: "Felipe Ruiz Bruzzone"
    background: primary
    left:
      - href: index.qmd
        text: Home
      - CV.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: full



