project:
  type: website
  output-dir: docs

website:
  navbar:
    title: "Felipe Ruiz Bruzzone"
    left:
      - href: index.qmd
        text: Home
      - CV.qmd
      - curriculum-en.qmd

format:
  html:
    theme:
      dark: darkly
      light: flatly
    css: css/styles.css
    toc: true
    page-layout: full