---
title: "Resume (ES)"
lang: es
format:
  html:
    toc: true
  pdf:
    author: Felipe Ruiz Bruzzone
    pdf-engine: weasyprint
css: css/cv.css
format-links: [pdf]
---

::: {.print-only .contact-block}
felipe.ruiz\@ug.uchile.cl
:::

## Posiciones actuales
**Director de Proyectos y Financiamiento** -- Jornada Parcial <br> *[Fundación Nodo XXI](https://www.nodoxxi.cl/)* [*2019 --- actualidad*]{.cvdate}

-   ONG cuyo  horizonte es la democratización social y política de la sociedad chilena para la construcción de un orden más justo, libre e igualitario.
-   Integro la Dirección Ejecutiva de Nodo XXI y estoy a cargo de la cartera de proyectos de financiamiento internacional para investigación e incidencia, por un monto anual aproximado de USD 50.000.

**Director Ejecutivo** -- Jornada Parcial <br> *[Estrategia Sur](https://estrategiasur.cl/)* [*2024 --- actualidad*]{.cvdate}

-  Consultora especializada en Ciencia de Datos para decisiones estratégicas. 
-  Soy Socio fundador y como Director Ejecutivo estoy a cargo de la gestión administrativa y comercial general de la empresa. 

## Formación

### Profesional

**[Summer Institute in Computational Social Sciences.](https://sicss.io/2026/buenos-aires/)** -- Especialización Profesional <br> *Instituto de Altos Estudios Sociales, Universidad Nacional de San Martín* [*2026*]{.cvdate}

**[AI Specialization](https://anthropic.skilljar.com/)** -- Especialización Profesional <br> *Anthropic Academy* [*2026*]{.cvdate}

**Análisis y síntesis de literatura científica usando inteligencia artificial generativa** -- Especialización Profesional <br> *Universidad Bernardo O'Higgins* [*2026*]{.cvdate}

**Dominando ChatGPT para la escritura y adjudicación de proyectos de Investigación** -- Especialización Profesional <br> *Universidad Diego Portales* [*2025*]{.cvdate}

**[Data Science Specialization](https://www.coursera.org/account/accomplishments/specialization/L53LGQM762N2)** -- Especialización Profesional <br> *John Hopkins University* [*2024*]{.cvdate}

**[Instructor en Programación y Ciencia de Datos](https://carpentries.org/instructors/)** -- Especialización Profesional <br> *The Carpentries* [*2023*]{.cvdate}

**[Program of Advanced Studies on Latin American Economies](https://elades.cepal.org/en)** -- Especialización Profesional <br> *Comisión Económica para América Latina, Naciones Unidas* [*2023*]{.cvdate}

**[Summer School in Computational Social Sciences, Methods for Analysing Multimedia Data](https://www.gesis.org/en/research/projects-and-exchange/conferences/events-archive/css-events)** -- Especialización Profesional <br> *GESIS Leibniz Institute for The Social Sciences* [*2019*]{.cvdate}

### Académica

**Doctorado -- Ciencias Sociales** <br> *Universidad de Chile* [*2026*]{.cvdate}

- Tesis: [*La clase capitalista en el Chile actual (2000-2019). Un estudio sobre los grupos económicos Luksic y Cencosud*]().
-   Agencia Nacional de Investigación y Desarrollo. *Beca de Doctorado Nacional* (2021-2025)

**Maestría -- Ciencias Sociales** <br> *Universidad de Chile* [*2019*]{.cvdate}

- Tesis: [*El empresariado del sistema de pensiones en Chile (2000-2018)*](https://repositorio.uchile.cl/handle/2250/178848) 
-   Agencia Nacional de Investigación y Desarrollo. *Beca de Magíster Nacional* (2017-2019)

**Licenciatura -- Sociología** <br> *Universidad de Chile* [*2016*]{.cvdate}

## Experiencia Laboral

### Consultoría en Ciencia de Datos

**Consultor** <br> *Múltiples clientes*[*2017 -- Present*]{.cvdate}

Presto servicios de recopilación, preprocesamiento, análisis estadístico y visualización de datos a distintos clientes del sector privado, científico y académico. Los últimos proyectos en los que he participado fueron:

-   2026-2026. *Tipo de cambio y perspectivas del desarrollo industrial en Uruguay (2000 a la actualidad)*. Cuesta Duarte, Instituto de Investigación y Formación del PIT-CNT. *Proyecto financiado por INEFOP*. [Reporte digital](https://feliperuizbruzzone.github.io/economia-uruguay/) y [Repositorio reproducible](https://doi.org/10.5281/zenodo.22431771)
-   2026-2025. *Sistematización Computacional de Estadísticas Tributarias según rama económica (2023-1998), en base a informes anuales de la administración Federal de Ingresos Públicos de Argentina*. Instituto de Ciencias, Universidad Nacional de General Sarmiento. *Proyecto PICT-2020-SERIE-A-00496*. [Repositorio reproducible](https://doi.org/10.5281/zenodo.22431875)
-   2024-2023. *Validación de registros administrativos y construcción de resultados de estadística: estructura ocupacional del Gobierno Central de Chile*. Facultad de Derecho, Universidad Alberto Hurtado. *Fondo Nacional de Desarrollo Científico y Tecnológico* (ID 1231868). [Reporte digital](https://rpubs.com/felipesruizb/gobierno-central).
-   2021-2022. *Validación, documentación y publicación de bases de datos en formato reproducible*.  Facultad de Ciencias Sociales, Universidad Diego Portales. *Fondo Nacional de Desarrollo Científico y Tecnológico* (ID 1171072).


### Docencia Universitaria y Profesional

***Docente responsable y Asistente de Docencia***  <br> *Diferentes instituciones*[*2016 -- actualidad*]{.cvdate}

Experiencia como docente en *teoría social*, *estratificación social*, *políticas públicas*, *Metodología de Investigación*, *Análisis Estadístico*, *Ciencia de Datos*, *Métodos Computacionales* e *Inteligencia Artificial Aplicada* en diferentes contextos educativos: universidades (grado y posgrado), especializaciones profesionales y clases particulares. He impartido cursos sobre:

- *Teoría Social* latinoamericana y chilena.
- *Estratificación y clases sociales* en América Latina.
- Análisis de *Políticas Públicas* del campo social y económico,
- Fundamentos del lenguaje de programación *R*.
- Diseños de investigación en el ámbito de las ciencias sociales, económicas y humanas.
- Proyectos de investigación basados en *Ciencia de Datos*.
- Métodos *estadísticos* básicos y avanzados para las Ciencias Sociales.
- Herramientas desde la *Ciencia Abierta* y el *Software Libre* para la Investigación Social.
- Introducción a las *Ciencias Sociales Computacionales*.
- *Inteligencia Artificial Aplicada* a investigación socioeconómica

## Trabajos en curso
- 2027-[La Nueva Izquierda en el gobierno: límites, desafíos y aprendizajes](). Santiago de Chile: Fondo de Cultura Económica. Coautor de libro con referato.
- 2027-[Trabajo y pensiones: avances y desafíos](). En [La Nueva Izquierda en el gobierno: límites, desafíos y aprendizajes](). Santiago de Chile: Fondo de Cultura Económica. Libro con referato.
- 2027-[Conducir el desarrollo productivo: dos experiencias dispares](). En [La Nueva Izquierda en el gobierno: límites, desafíos y aprendizajes](). Santiago de Chile: Fondo de Cultura Económica. Libro con referato.
- 2026-[Transformaciones en la reproducción de la población de Petorca (Chile) y la disputa por el agua durante la expansión de la frontera agrícola (1990-2022)](https://doi.org/10.31235/osf.io/m7hfq_v1). Borrador aceptado en [Waterlat-Gobacit Network Working Papers](https://waterlat.org/working-papers-series/). Co-autoría con: Javiera Rojas Cifuentes.
- 2026-[International expansion and wealth capture in Chilean economic groups during the 21st century](). Borrador en preparación para [Socioeconomic Review](https://academic.oup.com/ser).
- 2026-[Estadística Descriptiva para la investigación en Comunicación y Ciencias Sociales. Una breve introducción](). En [Metodología de Investigación en Comunicación y Opinión Pública](). Santiago de Chile: Ediciones Universidad Diego Portales. Libro con referato.

## Publicaciones recientes

- 2025-[Capitalist class structure in Chile (21st century): a descriptive and multivariate quantitative characterization](https://doi.org/10.1080/07360932.2025.2594524). *Forum for Social Economics*, Special Issue on the Social Consequences of Development in Latin America in the 21st Century.

- 2025-[Metodología computacional para el análisis de información financiera en formato XBRL. Un primer esfuerzo aplicado a grupos económicos de Chile](https://www.researchgate.net/publication/398951801_Analisis_computacional_de_informacion_financiera_en_formato_XBRL_Una_aplicacion_a_grupos_economicos_de_Chile_2000-2019). En [Investigación cuantitativa: estrategias metodológicas recientes para tesis doctorales en Ciencias Económicas y Sociales](http://hdl.handle.net/11086/559603). Argentina: Editorial de la Facultad de Ciencias Económicas de la Universidad Nacional de Córdoba. Libro con referato.

- 2024-[¿Qué interrupciones del proyecto (intelectual y político) de la Unidad Popular siguen siendo relevantes para el presente?](). En [La Unidad Popular Interrumpida](https://facso.uchile.cl/publicaciones/221189/la-unidad-popular-interrumpida). Santiago de Chile: Ediciones de la Facultad de Ciencias Sociales de la Universidad de Chile. Autor. Libro con referato.

- 2024-[Solidaridad en el pilar contributivo de pensiones. Aproximación progresista para discutir la reforma](https://library.fes.de/pdf-files/bueros/chile/21701.pdf). Documento de Política Pública. Friedrich Ebert Stiftüng y Fundación Nodo XXI. Coautor.

- 2024-[¿Qué hacer con los créditos y deudas estudiantiles? Condonar y reestructurar para recuperar la promesa de la educación superior](https://www.nodoxxi.cl/portada/2024/nodo-xxi-realiza-un-estudio-sobre-la-eficiencia-del-sistema-de-creditos-en-chile-y-el-impacto-del-proyecto-sobre-fin-al-cae-y-condonacion-de-deudas-estudiantiles/). Documento de Política Pública. Fundación Nodo XXI. Coautor.

- 2024-Financiarización y poder empresarial en el sistema de pensiones chileno. En [Formas y mecanismos de la dominación financiera en América Latina](https://www.iis.unam.mx/formas-y-mecanismos-de-la-dominacion-financiera-en-america-latina/). México: Instituto de Investigaciones Sociales de la Universidad Nacional Autónoma de México. Autor. Libro con referato.

- 2023-[The job of public transport, ride-hailing, and delivery drivers: Conditions during the COVID-19 pandemic and implications for a post-pandemic future](https://doi.org/10.1016/j.tbs.2022.11.004). *Travel, Behaviour, and Society*, vol. 31, pages 63-77. Coautor.

- 2021-[Financialization and the construction of peripheral business power in the Chilean pension system](https://doi.org/10.1007/978-3-030-71315-7). En *Dependent Capitalisms in Contemporary Latin America and Europe*. Palgrave Macmillan. Autor. Libro con referato.

- 2019-[RStudio para Estadística Descriptiva en Ciencias Sociales](https://bookdown.org/gboccardo/manual-ED-UCH/). 2a edición. Departmento de Sociología, Universidad de Chile. *Manual online interactivo*. Coautor.
